<a href="https://colab.research.google.com/github/poorvajain04/Introduction-to-deep-learning-and-genAI/blob/main/akgec_gen_ai_class_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#"HELLO!! NLP IS AMAZING"
import string
text="HELLO!! NLP IS AMAZING"
cleaned=text.lower()
cleaned=cleaned.translate(str.maketrans("","",string.punctuation))
cleaned

'hello nlp is amazing'

In [15]:
text="NLP    is very useful"
cleaned="".join(text.split())
cleaned

'NLPisveryuseful'

In [16]:
text="NLP IS USED IN CHATBOTS"
tokens=text.split()
print(tokens)
print("total token:",len(tokens))

['NLP', 'IS', 'USED', 'IN', 'CHATBOTS']
total token: 5


In [17]:
paragraph="NLP IS POWERFUL. IT IS USED IN AI"
sentences=paragraph.split(".")
sentences

['NLP IS POWERFUL', ' IT IS USED IN AI']

In [18]:
text="this is a very good product"
stop_words=["this","is","a","very"]
words=text.lower().split()
filtered=[]
for word in words:
  if word not in stop_words:
    filtered.append(word)
filtered

['good', 'product']

In [22]:
t="the product is good and delivery is very fast"
stopwords=["the","is","and","very"]
w=t.split()
filter=[]
for wrd in w:
    if wrd not in stopwords:
        filter.append(wrd)
filter

['product', 'good', 'delivery', 'fast']

**Sentiment Analysis**

In [23]:
review="the product is good"
p=["good","amazing","best"]
n=["bad","poor","pathetic"]
text=review.lower()
sentiment="neutral"
for word in p:
  if word in text:
    sentiment="positive"
for word in n:
  if word in text:
    sentiment="negative"
sentiment

'positive'

In [27]:
review=[
    "good product",
    "bad experience",
    "average product"
    ]
p=["good","best","nice"]
n=["bad","poor","average"]
for r in review:
  sentiment="neutral"
  t=r.lower()
  for word in p:
    if word in t:
      sentiment="positive"
  for word in n:
    if word in t:
      sentiment="negative"
  print("sentiment:",sentiment)


sentiment: positive
sentiment: negative
sentiment: negative


In [28]:
from numpy import vectorize
text=[
    "I LOVE NLP",
    "NLP IS USEFUL"
]
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(text)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['is' 'love' 'nlp' 'useful']
[[0 1 1 0]
 [1 0 1 1]]


In [29]:
text=[
    "good good product",
    "bad product"
]
vector=CountVectorizer()
X=vector.fit_transform(text)
print(vector.get_feature_names_out())
print(X.toarray())

['bad' 'good' 'product']
[[0 2 1]
 [1 0 1]]


In [31]:
#TF and IDF
#If any word appears many times, it can have have TF but a low IDF
#TF=TERM FREQUENCY
#IDF=INVERSE DOCUMENT FREQUENCY
texts=[
    "good product",
    "bad product",
    "good quality"
]
from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf=TfidfVectorizer()
X=Tfidf.fit_transform(texts)
print(Tfidf.get_feature_names_out())
print(X.toarray())


['bad' 'good' 'product' 'quality']
[[0.         0.70710678 0.70710678 0.        ]
 [0.79596054 0.         0.60534851 0.        ]
 [0.         0.60534851 0.         0.79596054]]


In [35]:
from sklearn.naive_bayes import MultinomialNB
messages=[
    "win money now",
    "limits offer wins",
    "hello friend",
    "how are you"
]
label=["spam","spam","not spam","not spam"]
vector=CountVectorizer()
X=vector.fit_transform(messages)
model=MultinomialNB()
model.fit(X,label)
test=["win offer"]
test_vector=vector.transform(test)
print(model.predict(test_vector[0]))

['spam']
